Repository Gin-n-Tonicc/Cool-School, pull requests merged in 2024-03, with the labels that each got.

#56 Integration tests
  .github/workflows/maven.yml
  client/.firebase/hosting.YnVpbGQ.cache
  client/src/components/auth/finish-register/finish-register-form/FinishRegisterForm.tsx
  client/src/components/auth/login/login-form/LoginForm.tsx
  client/src/components/http-provider/HttpProvider.tsx
  client/src/contexts/AuthContext.tsx
  client/src/hooks/useAuthenticate.ts
  client/src/hooks/useFetch.ts
  client/src/types/interfaces/auth/IAuthResponse.ts
  client/src/types/interfaces/auth/IAuthStorage.ts
  server/src/main/java/com/coolSchool/coolSchool/config/WebConfig.java
  server/src/main/java/com/coolSchool/coolSchool/controllers/AuthenticationController.java
  server/src/main/java/com/coolSchool/coolSchool/controllers/BlogController.java
  server/src/main/java/com/coolSchool/coolSchool/controllers/DemoController.java
  server/src/main/java/com/coolSchool/coolSchool/services/AuthenticationService.java
  server/src/main/java/com/coolSchool/coolSchool/services/impl/BlogServiceImpl.java
  server/src/main/java/com/coolSchool/coolSchool/services/impl/security/AuthenticationServiceImpl.java
  server/src/main/java/com/coolSchool/coolSchool/services/impl/security/TokenServiceImpl.java
  server/src/test/java/com/coolSchool/CoolSchool/controllerTest/AnswerControllerIntegrationTest.java
  server/src/test/java/com/coolSchool/CoolSchool/controllerTest/BlogControllerIntegrationTest.java
  server/src/test/java/com/coolSchool/CoolSchool/controllerTest/CategoryControllerIntegrationTest.java
  server/src/test/java/com/coolSchool/CoolSchool/controllerTest/CommentControllerIntegrationTest.java
  server/src/test/java/com/coolSchool/CoolSchool/controllerTest/CourseControllerIntegrationTest.java
  server/src/test/java/com/coolSchool/CoolSchool/controllerTest/CourseSubsectionControllerTest.java
  server/src/test/java/com/coolSchool/CoolSchool/controllerTest/FileControllerIntegrationTest.java
  server/src/test/java/com/coolSchool/CoolSchool/controllerTest/MessageControllerIntegrationTest.java
  server/src/test/java/com/coolSchool/CoolSchool/controllerTest/QuestionControllerIntegrationTest.java
  server/src/test/java/com/coolSchool/CoolSchool/controllerTest/QuizControllerIntegrationTest.java
  server/src/test/java/com/coolSchool/CoolSchool/controllerTest/ResourceControllerIntegrationTest.java
  server/src/test/java/com/coolSchool/CoolSchool/controllerTest/ReviewControllerIntegrationTest.java
  server/src/test/java/com/coolSchool/CoolSchool/controllerTest/UserControllerIntegrationTest.java
  server/src/test/java/com/coolSchool/CoolSchool/controllerTest/UserCourseControllerIntegrationTest.java
  server/src/test/java/com/coolSchool/CoolSchool/serviceTest/AuthenticationServiceImplTest.java
  server/src/test/java/com/coolSchool/CoolSchool/serviceTest/BlogServiceImplTest.java
  server/src/test/java/com/coolSchool/CoolSchool/serviceTest/CategoryServiceImplTest.java
  server/src/test/java/com/coolSchool/CoolSchool/serviceTest/CommentServiceImplTest.java
  server/src/test/java/com/coolSchool/CoolSchool/serviceTest/ResourceServiceImplTest.java
  server/src/test/java/com/coolSchool/CoolSchool/serviceTest/TokenServiceImplTest.java
Labels: testing

#66 FE Small Bugfixes and Enhancements
  client/src/components/admin/admin-edit-form/AdminEditForm.tsx
  client/src/components/admin/admin-table-api/AdminTableApi.tsx
  client/src/components/admin/admin-table/AdminTable.scss
  client/src/components/admin/admin-table/AdminTable.tsx
  client/src/components/admin/admin-table/admin-table-search/AdminTableSearch.tsx
  client/src/components/admin/admin-tables/AdminTableBlogs.tsx
  client/src/components/admin/admin-tables/AdminTableCategories.tsx
  client/src/components/admin/admin-tables/AdminTableCourses.tsx
  client/src/components/admin/admin-tables/AdminTableResources.tsx
  client/src/components/admin/admin-tables/AdminTableSubsections.tsx
  client/src/components/admin/admin-tables/AdminTableUsers.tsx
  client/src/components/blog/blog-create/BlogCreate.tsx
  client/src/components/blog/blog-item/BlogItem.scss
  client/src/components/blog/blog-right-sidebar/BlogRightSidebar.scss
  client/src/components/blog/blog-right-sidebar/BlogRightSidebar.tsx
  client/src/components/common/breadcrumb/Breadcrumb.scss
  client/src/components/common/category-select/CategorySelect.tsx
  client/src/components/common/header/Header.tsx
  client/src/components/contact-us/ContactUs.tsx
  client/src/components/courses/courses-create/CoursesCreate.tsx
  client/src/components/courses/courses-single/CoursesSingle.scss
  client/src/components/courses/courses-single/courses-list/courses-list-item/CoursesListItem.tsx
  client/src/components/courses/courses-single/courses-list/courses-list-item/courses-quizzes/courses-quizzes-control/CoursesQuizzesControl.tsx
  client/src/components/courses/courses-single/courses-list/courses-list-item/courses-resource/CoursesResource.tsx
  client/src/components/quiz/quiz-single/QuizSingle.tsx
  client/src/contexts/AuthContext.tsx
  client/src/locales/bg/translation.json
  client/src/locales/en/translation.json
  client/src/styles/_button.scss
  server/src/main/java/com/coolSchool/coolSchool/services/impl/BlogServiceImpl.java
Labels: enhancement, small bug

#68 BE Add Service Tests
  .github/workflows/maven.yml
  server/src/main/java/com/coolSchool/coolSchool/services/impl/AnswerServiceImpl.java
  server/src/main/java/com/coolSchool/coolSchool/services/impl/BlogServiceImpl.java
  server/src/main/java/com/coolSchool/coolSchool/services/impl/CourseServiceImpl.java
  server/src/main/java/com/coolSchool/coolSchool/services/impl/QuestionServiceImpl.java
  server/src/test/java/com/coolSchool/CoolSchool/serviceTest/AIAssistanceServiceImplTest.java
  server/src/test/java/com/coolSchool/CoolSchool/serviceTest/AnswerServiceImplTest.java
  server/src/test/java/com/coolSchool/CoolSchool/serviceTest/AuthenticationServiceImplTest.java
  server/src/test/java/com/coolSchool/CoolSchool/serviceTest/BlogServiceImplTest.java
  server/src/test/java/com/coolSchool/CoolSchool/serviceTest/CategoryServiceImplTest.java
  server/src/test/java/com/coolSchool/CoolSchool/serviceTest/CommentServiceImplTest.java
  server/src/test/java/com/coolSchool/CoolSchool/serviceTest/CourseServiceImplTest.java
  server/src/test/java/com/coolSchool/CoolSchool/serviceTest/CourseSubsectionServiceImplTest.java
  server/src/test/java/com/coolSchool/CoolSchool/serviceTest/QuestionServiceImplTest.java
  server/src/test/java/com/coolSchool/CoolSchool/serviceTest/QuizServiceImplTest.java
  server/src/test/java/com/coolSchool/CoolSchool/serviceTest/ReviewServiceImplTest.java
  server/src/test/java/com/coolSchool/CoolSchool/serviceTest/UserCourseServiceImplTest.java
Labels: testing

#75 fix Slack and Gmail bugs
  server/src/main/java/com/coolSchool/coolSchool/services/impl/CourseServiceImpl.java
  server/src/test/java/com/coolSchool/CoolSchool/serviceTest/CourseServiceImplTest.java
Labels: bug

#77 Fe design fixes
  client/src/components/home/home-banner/HomeBanner.scss
  client/src/components/home/home-blog/HomeBlog.scss
  client/src/components/home/home-blog/HomeBlog.tsx
  client/src/components/home/home-blog/home-blog-card/HomeBlogCard.scss
  client/src/components/home/home-blog/home-blog-card/HomeBlogCard.tsx
  client/src/components/home/home-features/HomeFeatures.scss
  client/src/components/home/home-features/HomeFeatures.tsx
  client/src/components/home/home-learning-feature/HomeLearningFeature.tsx
  client/src/components/home/styles/common_learning.scss
  client/src/styles/_common.scss
Labels: small bug
